feat: se agrega seccion de tecnologias
Trycatch-tv/trycatch_factory_site pull request #16
Opened 2024-05-01 03:37 UTC by Juliancho2

Cambios:

- Se crea estructura del componente de tecnologías y se importa en el index.
- 
preview:

![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/87348556/5a959507-69d9-49e6-a5e7-be17d79d05e5)

2024-05-03 03:40 UTC, judlup requested changes

2024-05-03 15:02 UTC, Juliancho2 commented
Realice los cambios requeridos.

2024-05-05 03:40 UTC, judlup requested changes

2024-05-05 03:40 UTC, judlup commented on src/components/landing/TechStackLanding.astro
>          {technologyData.map((item) => (
* Agregar en el objeto technologyData en cada elemento en el campo tecnologies los datos para renderizar desde ahí y poder quitar el Array que quema las imagenes de la línea :49

2024-05-07 02:46 UTC, judlup approved these changes
:) :)

2024-05-07 02:50 UTC, merged