4 bloque nuestro proceso del sitio
Trycatch-tv/trycatch_factory_site pull request #17
Opened 2024-05-01 17:06 UTC by ramtako8922

Creancion de componentes nuestros procesos de acuerdo mockup  v1.0.1

2024-05-03 03:40 UTC, judlup requested changes

2024-05-04 19:24 UTC, ramtako8922 commented on src/components/Nuestros-procesos.astro
> +---
Hola apreciado Julian 
Ya se realizaron los ajustes

2024-05-05 03:52 UTC, judlup requested changes

2024-05-05 03:52 UTC, judlup commented on src/components/landing/NuestroProcesoLanding.astro
> +      <!---Espacio para imagen o video -->
* Agregar imagen de hardcodeada

2024-05-05 03:52 UTC, judlup commented on src/components/landing/NuestroProcesoLanding.astro
> +        <!---Espacio para imagen o video -->
* Agregar imagen de hardcodeada

2024-05-05 14:49 UTC, ramtako8922 commented on src/components/landing/NuestroProcesoLanding.astro
> +      <!---Espacio para imagen o video -->
Listo procedo a ello

2024-05-07 02:53 UTC, merged