Se agregó bloque de preguntas y respuestas
Trycatch-tv/trycatch_factory_site pull request #18
Opened 2024-05-01 17:54 UTC by Orliluq

Bloque de preguntas y respuestas, icon utilizado arrows. 

![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/122529721/8963ce0c-4ad7-432b-bac8-a56dd02050cd)
 
quedo atenta a cualquier cambio.

2024-05-03 03:38 UTC, judlup requested changes
Estos son mis comentarios

2024-05-05 02:32 UTC, Orliluq commented
Cambios propuestos realizados, además de npm install dependencias de lucide-astro, astro-icon y @iconify-json/mdi

![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/122529721/cafed4d4-3fb6-4134-b9cf-0a399f94376a)

2024-05-05 04:15 UTC, judlup requested changes

2024-05-05 04:15 UTC, judlup commented on src/components/landing/FAQLanding.astro
> +---
* El recuadro más grande no va
* El color del fondo de la acordeón es distinto al del mockup
* El margen del acordeón no es igual al del mockup
* Falta la línea blanca entre el título y el texto, validar si se puede incluir la línea de acuerdo a las limitaciones del componente utilziado.

![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/3951903/c92b5ea5-16f6-4eff-8f04-0e1967048647)

2024-05-05 21:46 UTC, Orliluq commented
- El recuadro más pequeño
- El color del fondo de la acordeón creo está igual al del mockup
- El margen del acordeón es igual al del mockup
- Línea blanca entre el título y el texto.

![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/122529721/7dc2923f-20f1-414f-a075-f4d10f58ddb1)

2024-05-07 02:56 UTC, judlup approved these changes
:) :)

2024-05-07 03:35 UTC, merged