TC-09 FOOTER-DEL-SITIO
Trycatch-tv/trycatch_factory_site pull request #22
Opened 2024-05-04 21:19 UTC by Angelxd0714

Se hace mejoras, con respecto al responsive, espacios se mejora los espacios.

2024-05-05 04:55 UTC, judlup requested changes

2024-05-05 04:55 UTC, judlup commented on src/components/global/Footer.astro
>  ---
![image](https://github.com/Trycatch-tv/trycatch_factory_site/assets/3951903/d7f85320-7871-4818-b61a-cc0df1520431)

1. Ajustar el margen entre el borde del component y el título acorde al mockup
2. Ajustar el espaciado entre los iconos de acuerdo al mockup
3. Ajustar la posición del botón de contacto para WhatsApp y hacerlo un poco más grande
4. Ajustar el botón de contacto de WhatsApp para que se desplace con la página usando position fixed

2024-05-05 04:55 UTC, judlup commented on src/components/global/Footer.astro
> +const classIcon = "text-white text-xl mx-2"
* Esta clase definirla en el mismo componente que la utiliza

2024-05-05 04:55 UTC, judlup commented on src/components/global/Footer.astro
> +const classIcon = "text-white text-xl mx-2"
* Esta clase definirla en el mismo componente que la utiliza

2024-05-06 04:04 UTC, Angelxd0714 commented
fix: se sube todo los puntos corregidos.

2024-05-07 03:16 UTC, judlup approved these changes
:) :)

2024-05-07 03:35 UTC, merged